/* Generated By:JavaCC: Do not edit this line. FormatCIAWorldFactsConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FormatCIAWorldFactsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING = 5;
  /** RegularExpression Id. */
  int QUOTE = 6;
  /** RegularExpression Id. */
  int ERROR = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\n\\r\"",
    "\"\\r\\n\"",
    "<STRING>",
    "\"\\\"\"",
    "<ERROR>",
  };

}
